# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: decode_tvbox

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: run my .py
      run: |
        cd py
        python decode_tvbox.py
        mv decode_tvbox.txt ../res
        cd ..
        date > run_time.txt
        cp run_time.txt ./res
        git add run_time.txt ./res/run_time.txt ./res/decode_tvbox.txt
        git commit -m "auto update"
        
