# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: decode_tvbox

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.DECODE_TVBOX_TOKEN }}

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: run my .py
      run: |
        cd ./py
        python decode_tvbox.py
        mv decode_tvbox.txt ../result/
        cd ..
        date > run_time.txt
        
    - name: Upload file
      run: |
        git config --global user.email "gsp1004@qq.com"
        git config --global user.name "gsp"
        git add run_time.txt ./result/decode_tvbox.txt
        git commit -m "auto update"
        git push
